sync: 2024-12-18 15:53:00

diff --git a/bash-scripts/aoc b/bash-scripts/aoc
--- a/bash-scripts/aoc
+++ b/bash-scripts/aoc
@@ -13,11 +13,33 @@ input="input.$2"
 LATEST_FILE_MOD=0
 LATEST_INPUT_MOD=0
 
-
+# Compile the file, run it, and display execution time
 run_code() {
+    echo -e "\nCompiling source..."
 
+    clang++ -o main \
+        -std=c++20 \
+        -O3 \
+        $file
+
+    if [[ $? != 0 ]] then
+        echo -e "Compilation failed.\n"
+        continue
+    fi
+    
+    echo -e "Running...\n"
+
+    start_time_us=$(echo $EPOCHREALTIME | tr -d '.')
+    ./main < $input
+    end_time_us=$(echo $EPOCHREALTIME | tr -d '.')
+    rm main
+
+    delta_ms=$(( (end_time_us - start_time_us) / 1000 ))
+
+    printf '\n\n┌%*s\n' 15 | tr ' ' '-'
+    echo -e "| Took \e[31m$delta_ms\e[0m ms"
+    printf '└%*s' $(($COLUMNS - 1)) | tr ' ' '-'
 }
-
 
 while true; do
     FILE_MOD=`stat -c %Z $file`
@@ -27,30 +49,6 @@ while true; do
         LATEST_FILE_MOD=$FILE_MOD
         LATEST_INPUT_MOD=$INPUT_MOD
 
-        echo -e "\nCompiling source..."
-
-        clang++ -o main \
-            -std=c++20 \
-            -O3 \
-            $file
-
-        if [[ $? != 0 ]] then
-            echo -e "Compilation failed.\n"
-            continue
-        fi
-        
-        echo -e "Running...\n"
-
-        start_time_us=$(echo $EPOCHREALTIME | tr -d '.')
-        ./main < $input
-        end_time_us=$(echo $EPOCHREALTIME | tr -d '.')
-        rm main
-
-        delta_ms=$(( (end_time_us - start_time_us) / 1000 ))
-
-        printf '\n\n┌%*s\n' 15 | tr ' ' '-'
-        echo -e "| Took \e[31m$delta_ms\e[0m ms"
-        printf '└%*s' $(($COLUMNS - 1)) | tr ' ' '-'
     fi
     sleep 0.2
 done
